---
- hosts: webserver
  become: yes
  tasks:
   - name: install the webserver on Ubuntu
     apt:
      name: "{{ubuntuwebserver}}"
      state: present
     when: ansible_os_family =="Debian"

   - name: start the webserver on Ubuntu
     service:
      name: "{{ubuntuwebserver}}"
      state: started
     when: ansible_os_family =="Debian"

   